var annotated_dup =
[
    [ "ADC_Common_TypeDef", "d3/d75/struct_a_d_c___common___type_def.html", "d3/d75/struct_a_d_c___common___type_def" ],
    [ "ADC_TypeDef", "dc/d6f/struct_a_d_c___type_def.html", "dc/d6f/struct_a_d_c___type_def" ],
    [ "CRC_TypeDef", "d9/d06/struct_c_r_c___type_def.html", "d9/d06/struct_c_r_c___type_def" ],
    [ "DBGMCU_TypeDef", "da/d4e/struct_d_b_g_m_c_u___type_def.html", "da/d4e/struct_d_b_g_m_c_u___type_def" ],
    [ "dio_channel_info_t", "d5/dba/structdio__channel__info__t.html", "d5/dba/structdio__channel__info__t" ],
    [ "dio_config_t", "d9/dec/structdio__config__t.html", "d9/dec/structdio__config__t" ],
    [ "DMA_Channel_TypeDef", "db/da7/struct_d_m_a___channel___type_def.html", "db/da7/struct_d_m_a___channel___type_def" ],
    [ "DMA_TypeDef", "d5/df6/struct_d_m_a___type_def.html", "d5/df6/struct_d_m_a___type_def" ],
    [ "ev1527_t", "d6/d21/structev1527__t.html", "d6/d21/structev1527__t" ],
    [ "exti_config_t", "d8/ddf/structexti__config__t.html", "d8/ddf/structexti__config__t" ],
    [ "EXTI_TypeDef", "db/ddd/struct_e_x_t_i___type_def.html", "db/ddd/struct_e_x_t_i___type_def" ],
    [ "FLASH_TypeDef", "d5/dc8/struct_f_l_a_s_h___type_def.html", "d5/dc8/struct_f_l_a_s_h___type_def" ],
    [ "GPIO_TypeDef", "d6/d59/struct_g_p_i_o___type_def.html", "d6/d59/struct_g_p_i_o___type_def" ],
    [ "I2C_TypeDef", "df/d6b/struct_i2_c___type_def.html", "df/d6b/struct_i2_c___type_def" ],
    [ "IWDG_TypeDef", "d4/da9/struct_i_w_d_g___type_def.html", "d4/da9/struct_i_w_d_g___type_def" ],
    [ "OB_TypeDef", "da/db2/struct_o_b___type_def.html", "da/db2/struct_o_b___type_def" ],
    [ "PWR_TypeDef", "d4/de6/struct_p_w_r___type_def.html", "d4/de6/struct_p_w_r___type_def" ],
    [ "rcc_config_t", "df/d56/structrcc__config__t.html", "df/d56/structrcc__config__t" ],
    [ "rcc_peri_t", "d1/d28/structrcc__peri__t.html", "d1/d28/structrcc__peri__t" ],
    [ "RCC_TypeDef", "d7/d46/struct_r_c_c___type_def.html", "d7/d46/struct_r_c_c___type_def" ],
    [ "RTC_TypeDef", "d5/db2/struct_r_t_c___type_def.html", "d5/db2/struct_r_t_c___type_def" ],
    [ "SPI_TypeDef", "df/d83/struct_s_p_i___type_def.html", "df/d83/struct_s_p_i___type_def" ],
    [ "SYSCFG_TypeDef", "d4/dd3/struct_s_y_s_c_f_g___type_def.html", "d4/dd3/struct_s_y_s_c_f_g___type_def" ],
    [ "TIM_TypeDef", "dd/d2a/struct_t_i_m___type_def.html", "dd/d2a/struct_t_i_m___type_def" ],
    [ "timer_config_t", "d4/de4/structtimer__config__t.html", "d4/de4/structtimer__config__t" ],
    [ "USART_TypeDef", "dc/d9c/struct_u_s_a_r_t___type_def.html", "dc/d9c/struct_u_s_a_r_t___type_def" ],
    [ "WWDG_TypeDef", "d9/d7b/struct_w_w_d_g___type_def.html", "d9/d7b/struct_w_w_d_g___type_def" ]
];