name: ClangFormat

on: [push]

jobs:
  ClangFormat:
    name: ClangFormat

    runs-on: ubuntu-latest
    container:
      image: mohammadniaraki/stm32_build:latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ClangFormat scan
        run: make clean && make prepare && make clangformat
