name: CppCheck

on: [push]

jobs:
  CppCheck:
    name: CppCheck

    runs-on: ubuntu-latest
    container:
      image: mohammadniaraki/stm32_build:latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: CppCheck scan
        run: make clean && make prepare && make cppcheck
