name: Doxygen

on: [push]

jobs:
  Doxygen:
    name: Doxygen

    runs-on: ubuntu-latest
    container:
      image: mohammadniaraki/stm32_build:latest

    permissions:
      actions: read
      contents: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generating documents by doxygen
        run: make clean && make prepare && make docs

      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          single-commit: true
          folder: build/docs/html
